### ISSUE TITLE
Aliases not loaded until that tab is activated

### ISSUE THREAD

**Issue by alexlafroscia** [littleStudent/now_dashboard#4]
Hey, I saw your project on Twitter today and figured I'd check it out. Just a heads-up; it seems only to load your aliases once you hit the `Aliases` tab at the top of the page, so you don't see aliases for any of the deployments until you navigate there and back again.

**Comment by littleStudent** [comment]
Thx for the report. This seems to happen when coming from the login only.
Does it work when refreshing the page?

**Comment by alexlafroscia** [comment]
Yup! Now it's loading them right after logging in. Thanks!
