### ISSUE TITLE
Awesome! One feature request

### ISSUE THREAD

**Issue by purplecones** [littleStudent/now_dashboard#6]
Hey I was thinking of building something like this as well and came across your version. I have so many deployments that deleting them all is a hassle so this really helps. 👏 

However, I still found myself pressing delete over and over. One project I have had like 50+ unused  deployments just because I never cleaned up. What would be great is to be able to select multiple deployments and delete all at once instead of one by one. Perhaps with a checkbox next to each deployment and a delete button at the top that appears.

**Comment by littleStudent** [comment]
I have thought about something like this. Most of the time clicking the delete button though the list has been fast enough for me though.
I will try to find the time to come up with a solution.

**Comment by shawninder** [comment]
How is clicking a checkbox faster than clicking a button? Unless you "select all" or something, but then I guess you would need some kind of filter to list only the deployments you want to delete, then select all then delete. Just a thought, but maybe a filtering feature would be a prerequisite here?
